### ISSUE TITLE
WebStorm 11 对 Node.js 的和谐度又提高了不少在 Preferences 中设置 Code Assistance 后不仅有代码的 智能补全还有如 java 一般的分析依赖智能补全依赖库甚至会提示安装依赖包写代码更省心http://t.cn/RUSCjd9

### ISSUE THREAD

**Issue by barretlee** [barretlee/weibo#84]
<img src="http://ww4.sinaimg.cn/large/6c0378f8gw1exr2tqocx1j20zk0aaq6c.jpg"> WebStorm 11 &#23545; Node.js &#30340;&#21644;&#35856;&#24230;&#21448;&#25552;&#39640;&#20102;&#19981;&#23569;&#12290;&#22312; Preferences &#20013;&#35774;&#32622; Code Assistance &#21518;&#65292;&#19981;&#20165;&#26377;&#20195;&#30721;&#30340; &#26234;&#33021;&#34917;&#20840;&#65292;&#36824;&#26377;&#22914; java &#19968;&#33324;&#30340;&#20998;&#26512;&#20381;&#36182;&#65292;&#26234;&#33021;&#34917;&#20840;&#20381;&#36182;&#24211;&#65292;&#29978;&#33267;&#20250;&#25552;&#31034;&#23433;&#35013;&#20381;&#36182;&#21253;&#65292;&#20889;&#20195;&#30721;&#26356;&#30465;&#24515;&#12290;http://t.cn/RUSCjd9 November 6, 2015 at 11:08AM via Weibo http://api.weibo.com/2/statuses/go?uid=1812166904&amp;id=3906137789677682

**Comment by JamesHT** [comment]
棒棒哒
